<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L9SRDqiService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.l9SRDqi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l9SRDqi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Infrastructure\\Http\\HomePageController::index' => ['privates', '.service_locator.N6A7.85.App\\Infrastructure\\Http\\HomePageController::index()', 'getHomePageControllerindexService', true],
            'App\\Infrastructure\\Http\\Security\\Controller\\SecurityController::register' => ['privates', '.service_locator.n_LpSm1.App\\Infrastructure\\Http\\Security\\Controller\\SecurityController::register()', 'getSecurityControllerregisterService', true],
            'App\\Infrastructure\\Http\\Security\\Controller\\SecurityController::login' => ['privates', '.service_locator.xkWA7vv.App\\Infrastructure\\Http\\Security\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Infrastructure\\Http\\HomePageController:index' => ['privates', '.service_locator.N6A7.85.App\\Infrastructure\\Http\\HomePageController::index()', 'getHomePageControllerindexService', true],
            'App\\Infrastructure\\Http\\Security\\Controller\\SecurityController:register' => ['privates', '.service_locator.n_LpSm1.App\\Infrastructure\\Http\\Security\\Controller\\SecurityController::register()', 'getSecurityControllerregisterService', true],
            'App\\Infrastructure\\Http\\Security\\Controller\\SecurityController:login' => ['privates', '.service_locator.xkWA7vv.App\\Infrastructure\\Http\\Security\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Infrastructure\\Http\\HomePageController::index' => '?',
            'App\\Infrastructure\\Http\\Security\\Controller\\SecurityController::register' => '?',
            'App\\Infrastructure\\Http\\Security\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Infrastructure\\Http\\HomePageController:index' => '?',
            'App\\Infrastructure\\Http\\Security\\Controller\\SecurityController:register' => '?',
            'App\\Infrastructure\\Http\\Security\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
