<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ZenstruckFoundry_ConfigurationService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public '.zenstruck_foundry.configuration' shared service.
     *
     * @return \Zenstruck\Foundry\Configuration
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/Configuration.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/FactoryRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/InMemory/InMemoryFactoryRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/FactoryRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/fakerphp/faker/src/Faker/Generator.php';
        include_once \dirname(__DIR__, 4).'/vendor/fakerphp/faker/src/Faker/Factory.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/Object/Instantiator.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/StoryRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/Persistence/PersistenceManager.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/Persistence/ResetDatabase/ResetDatabaseManager.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/InMemory/InMemoryRepositoryRegistry.php';

        return $container->services['.zenstruck_foundry.configuration'] = new \Zenstruck\Foundry\Configuration(new \Zenstruck\Foundry\InMemory\InMemoryFactoryRegistry(new \Zenstruck\Foundry\FactoryRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\Infrastructure\\Factory\\CVFactory'] ??= new \App\Infrastructure\Factory\CVFactory());
            yield 1 => ($container->privates['App\\Infrastructure\\Factory\\StudentFactory'] ??= new \App\Infrastructure\Factory\StudentFactory());
            yield 2 => ($container->privates['App\\Infrastructure\\Factory\\TeacherFactory'] ??= new \App\Infrastructure\Factory\TeacherFactory());
            yield 3 => ($container->privates['App\\Infrastructure\\Factory\\TeacherHasTeacherExpertisesFactory'] ??= new \App\Infrastructure\Factory\TeacherHasTeacherExpertisesFactory());
            yield 4 => ($container->privates['App\\Infrastructure\\Factory\\UserFactory'] ?? $container->load('getUserFactoryService'));
        }, 5))), \Faker\Factory::create(), \Zenstruck\Foundry\Object\Instantiator::withConstructor(), new \Zenstruck\Foundry\StoryRegistry(new RewindableGenerator(fn () => new \EmptyIterator(), 0), []), new \Zenstruck\Foundry\Persistence\PersistenceManager(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.zenstruck_foundry.persistence_strategy.orm'] ?? $container->load('get_ZenstruckFoundry_PersistenceStrategy_OrmService'));
        }, 1), new \Zenstruck\Foundry\Persistence\ResetDatabase\ResetDatabaseManager(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Zenstruck\\Foundry\\ORM\\ResetDatabase\\OrmResetter'] ?? $container->load('getOrmResetterService'));
        }, 1), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Zenstruck\\Foundry\\ORM\\ResetDatabase\\OrmResetter'] ?? $container->load('getOrmResetterService'));
        }, 1))), true, $container->getEnv('default:zenstruck_foundry.faker.seed:int:FOUNDRY_FAKER_SEED'), new \Zenstruck\Foundry\InMemory\InMemoryRepositoryRegistry(($container->privates['.service_locator.GIuJv7e'] ??= new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [], []))));
    }
}
