<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get__ZenstruckFoundry_Story_LoadStorycommand_LazyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '..zenstruck_foundry.story.load_story-command.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['..zenstruck_foundry.story.load_story-command.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('foundry:load-stories', [], 'Load stories which are marked with #[AsFixture] attribute.', false, #[\Closure(name: '.zenstruck_foundry.story.load_story-command', class: 'Zenstruck\\Foundry\\Command\\LoadStoryCommand')] fn (): \Zenstruck\Foundry\Command\LoadStoryCommand => ($container->privates['.zenstruck_foundry.story.load_story-command'] ?? $container->load('get_ZenstruckFoundry_Story_LoadStorycommandService')));
    }
}
