<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ZenstruckFoundry_Story_LoadStorycommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.zenstruck_foundry.story.load_story-command' shared service.
     *
     * @return \Zenstruck\Foundry\Command\LoadStoryCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/Command/LoadStoryCommand.php';

        $container->privates['.zenstruck_foundry.story.load_story-command'] = $instance = new \Zenstruck\Foundry\Command\LoadStoryCommand([], [], new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Zenstruck\\Foundry\\ORM\\ResetDatabase\\OrmResetter'] ?? $container->load('getOrmResetterService'));
        }, 1), ($container->services['kernel'] ?? $container->get('kernel', 1)));

        $instance->setName('foundry:load-stories');
        $instance->setDescription('Load stories which are marked with #[AsFixture] attribute.');

        return $instance;
    }
}
