<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get__ZenstruckFoundry_MakeFactoryCommand_LazyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '..zenstruck_foundry.make_factory_command.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['..zenstruck_foundry.make_factory_command.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('make:factory', [], 'Creates a Foundry object factory', true, #[\Closure(name: '.zenstruck_foundry.make_factory_command', class: 'Zenstruck\\Foundry\\Command\\StubCommand')] fn (): \Zenstruck\Foundry\Command\StubCommand => ($container->privates['.zenstruck_foundry.make_factory_command'] ?? $container->load('get_ZenstruckFoundry_MakeFactoryCommandService')));
    }
}
