<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddStudyingModeToTeacherService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Application\Teacher\UseCase\AddStudyingModeToTeacher' shared autowired service.
     *
     * @return \App\Application\Teacher\UseCase\AddStudyingModeToTeacher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Teacher/UseCase/AddStudyingModeToTeacher.php';

        return $container->privates['App\\Application\\Teacher\\UseCase\\AddStudyingModeToTeacher'] = new \App\Application\Teacher\UseCase\AddStudyingModeToTeacher(($container->privates['App\\Infrastructure\\Repository\\TeacherRepository'] ?? $container->load('getTeacherRepositoryService')));
    }
}
