<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCVFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Infrastructure\Factory\CVFactory' shared autowired service.
     *
     * @return \App\Infrastructure\Factory\CVFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/Factory.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/ObjectFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/Persistence/PersistentObjectFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/Persistence/PersistentProxyObjectFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Factory/CVFactory.php';

        return $container->privates['App\\Infrastructure\\Factory\\CVFactory'] = new \App\Infrastructure\Factory\CVFactory();
    }
}
