<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateUserService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Application\User\UseCase\CreateUser' shared autowired service.
     *
     * @return \App\Application\User\UseCase\CreateUser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/User/UseCase/CreateUser.php';

        return $container->privates['App\\Application\\User\\UseCase\\CreateUser'] = new \App\Application\User\UseCase\CreateUser(($container->privates['App\\Infrastructure\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
