<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpertiseRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Infrastructure\Repository\ExpertiseRepository' shared autowired service.
     *
     * @return \App\Infrastructure\Repository\ExpertiseRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryProxy.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Repository/ExpertiseRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Repository/ExpertiseRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Infrastructure\\Repository\\ExpertiseRepository'])) {
            return $container->privates['App\\Infrastructure\\Repository\\ExpertiseRepository'];
        }

        return $container->privates['App\\Infrastructure\\Repository\\ExpertiseRepository'] = new \App\Infrastructure\Repository\ExpertiseRepository($a, ($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
