<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetDemoExpertisesListService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Application\Expertise\UseCase\GetDemoExpertisesList' shared autowired service.
     *
     * @return \App\Application\Expertise\UseCase\GetDemoExpertisesList
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Expertise/UseCase/GetDemoExpertisesList.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Services/HelperServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Services/HelperService.php';

        return $container->privates['App\\Application\\Expertise\\UseCase\\GetDemoExpertisesList'] = new \App\Application\Expertise\UseCase\GetDemoExpertisesList(($container->privates['App\\Infrastructure\\Services\\HelperService'] ??= new \App\Infrastructure\Services\HelperService()));
    }
}
