<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetAmount2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Application\Student\UseCase\GetAmount' shared autowired service.
     *
     * @return \App\Application\Student\UseCase\GetAmount
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Student/UseCase/GetAmount.php';

        return $container->privates['App\\Application\\Student\\UseCase\\GetAmount'] = new \App\Application\Student\UseCase\GetAmount(($container->privates['App\\Infrastructure\\Repository\\StudentRepository'] ?? $container->load('getStudentRepositoryService')));
    }
}
