<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetTeacherService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Application\Teacher\UseCase\GetTeacher' shared autowired service.
     *
     * @return \App\Application\Teacher\UseCase\GetTeacher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Teacher/UseCase/GetTeacher.php';

        return $container->privates['App\\Application\\Teacher\\UseCase\\GetTeacher'] = new \App\Application\Teacher\UseCase\GetTeacher(($container->privates['App\\Infrastructure\\Repository\\TeacherRepository'] ?? $container->load('getTeacherRepositoryService')));
    }
}
