<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetAllStudyingModesService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Application\StudyingMode\UseCase\GetAllStudyingModes' shared autowired service.
     *
     * @return \App\Application\StudyingMode\UseCase\GetAllStudyingModes
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/StudyingMode/UseCase/GetAllStudyingModes.php';

        return $container->privates['App\\Application\\StudyingMode\\UseCase\\GetAllStudyingModes'] = new \App\Application\StudyingMode\UseCase\GetAllStudyingModes(($container->privates['App\\Infrastructure\\Repository\\StudyingModeRepository'] ?? $container->load('getStudyingModeRepositoryService')));
    }
}
