<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetAllCountriesService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Application\Country\UseCase\GetAllCountries' shared autowired service.
     *
     * @return \App\Application\Country\UseCase\GetAllCountries
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Country/UseCase/GetAllCountries.php';

        return $container->privates['App\\Application\\Country\\UseCase\\GetAllCountries'] = new \App\Application\Country\UseCase\GetAllCountries(($container->privates['App\\Infrastructure\\Repository\\CountryRepository'] ?? $container->load('getCountryRepositoryService')));
    }
}
