<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetAllPaymentTypesService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Application\PaymentType\UseCase\GetAllPaymentTypes' shared autowired service.
     *
     * @return \App\Application\PaymentType\UseCase\GetAllPaymentTypes
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/PaymentType/UseCase/GetAllPaymentTypes.php';

        return $container->privates['App\\Application\\PaymentType\\UseCase\\GetAllPaymentTypes'] = new \App\Application\PaymentType\UseCase\GetAllPaymentTypes(($container->privates['App\\Infrastructure\\Repository\\PaymentTypeRepository'] ?? $container->load('getPaymentTypeRepositoryService')));
    }
}
