<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetHomePageHtmlDataService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Application\Homepage\UseCase\GetHomePageHtmlData' shared autowired service.
     *
     * @return \App\Application\Homepage\UseCase\GetHomePageHtmlData
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Homepage/UseCase/GetHomePageHtmlData.php';

        return $container->privates['App\\Application\\Homepage\\UseCase\\GetHomePageHtmlData'] = new \App\Application\Homepage\UseCase\GetHomePageHtmlData();
    }
}
