<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetDemoCitiesListService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Application\City\UseCase\GetDemoCitiesList' shared autowired service.
     *
     * @return \App\Application\City\UseCase\GetDemoCitiesList
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/City/UseCase/GetDemoCitiesList.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Services/HelperServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Services/HelperService.php';

        return $container->privates['App\\Application\\City\\UseCase\\GetDemoCitiesList'] = new \App\Application\City\UseCase\GetDemoCitiesList(($container->privates['App\\Infrastructure\\Services\\HelperService'] ??= new \App\Infrastructure\Services\HelperService()));
    }
}
