<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetDemoStudyingModesListService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Application\StudyingMode\UseCase\GetDemoStudyingModesList' shared autowired service.
     *
     * @return \App\Application\StudyingMode\UseCase\GetDemoStudyingModesList
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/StudyingMode/UseCase/GetDemoStudyingModesList.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Services/HelperServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Services/HelperService.php';

        return $container->privates['App\\Application\\StudyingMode\\UseCase\\GetDemoStudyingModesList'] = new \App\Application\StudyingMode\UseCase\GetDemoStudyingModesList(($container->privates['App\\Infrastructure\\Services\\HelperService'] ??= new \App\Infrastructure\Services\HelperService()));
    }
}
