<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetDemoPaymentTypesListService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Application\PaymentType\UseCase\GetDemoPaymentTypesList' shared autowired service.
     *
     * @return \App\Application\PaymentType\UseCase\GetDemoPaymentTypesList
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/PaymentType/UseCase/GetDemoPaymentTypesList.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Services/HelperServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Services/HelperService.php';

        return $container->privates['App\\Application\\PaymentType\\UseCase\\GetDemoPaymentTypesList'] = new \App\Application\PaymentType\UseCase\GetDemoPaymentTypesList(($container->privates['App\\Infrastructure\\Services\\HelperService'] ??= new \App\Infrastructure\Services\HelperService()));
    }
}
