<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomePageControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Infrastructure\Http\HomePageController' shared autowired service.
     *
     * @return \App\Infrastructure\Http\HomePageController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Http/HomePageController.php';

        $container->services['App\\Infrastructure\\Http\\HomePageController'] = $instance = new \App\Infrastructure\Http\HomePageController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Infrastructure\\Http\\HomePageController', $container));

        return $instance;
    }
}
