<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomePageControllerindexService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.N6A7.85.App\Infrastructure\Http\HomePageController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N6A7.85.App\\Infrastructure\\Http\\HomePageController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cache' => ['services', 'cache.app', 'getCache_AppService', true],
            'GetAllExpertisesCase' => ['privates', 'App\\Application\\Expertise\\UseCase\\GetAllExpertises', 'getGetAllExpertisesService', true],
            'GetAllPaymentTypesCase' => ['privates', 'App\\Application\\PaymentType\\UseCase\\GetAllPaymentTypes', 'getGetAllPaymentTypesService', true],
            'GetCitiesAmountCase' => ['privates', 'App\\Application\\City\\UseCase\\GetAmount', 'getGetAmountService', true],
            'GetStudentAmountCase' => ['privates', 'App\\Application\\Student\\UseCase\\GetAmount', 'getGetAmount2Service', true],
            'GetHomePageHtmlData' => ['privates', 'App\\Application\\Homepage\\UseCase\\GetHomePageHtmlData', 'getGetHomePageHtmlDataService', true],
        ], [
            'cache' => '?',
            'GetAllExpertisesCase' => 'App\\Application\\Expertise\\UseCase\\GetAllExpertises',
            'GetAllPaymentTypesCase' => 'App\\Application\\PaymentType\\UseCase\\GetAllPaymentTypes',
            'GetCitiesAmountCase' => 'App\\Application\\City\\UseCase\\GetAmount',
            'GetStudentAmountCase' => 'App\\Application\\Student\\UseCase\\GetAmount',
            'GetHomePageHtmlData' => 'App\\Application\\Homepage\\UseCase\\GetHomePageHtmlData',
        ]))->withContext('App\\Infrastructure\\Http\\HomePageController::index()', $container);
    }
}
