<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHelperServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Infrastructure\Services\HelperService' shared autowired service.
     *
     * @return \App\Infrastructure\Services\HelperService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Domain/Services/HelperServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Services/HelperService.php';

        return $container->privates['App\\Infrastructure\\Services\\HelperService'] = new \App\Infrastructure\Services\HelperService();
    }
}
