<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrmResetterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Zenstruck\Foundry\ORM\ResetDatabase\OrmResetter' shared service.
     *
     * @return \Zenstruck\Foundry\ORM\ResetDatabase\SchemaDatabaseResetter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/Persistence/ResetDatabase/BeforeFirstTestResetter.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/Persistence/ResetDatabase/BeforeEachTestResetter.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/ORM/ResetDatabase/OrmResetter.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/ORM/ResetDatabase/BaseOrmResetter.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/ORM/ResetDatabase/SchemaDatabaseResetter.php';

        return $container->privates['Zenstruck\\Foundry\\ORM\\ResetDatabase\\OrmResetter'] = new \Zenstruck\Foundry\ORM\ResetDatabase\SchemaDatabaseResetter(($container->services['doctrine'] ?? self::getDoctrineService($container)), ['default'], ['default']);
    }
}
