<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationFormTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Infrastructure\Form\RegistrationFormType' shared autowired service.
     *
     * @return \App\Infrastructure\Form\RegistrationFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Form/RegistrationFormType.php';

        return $container->privates['App\\Infrastructure\\Form\\RegistrationFormType'] = new \App\Infrastructure\Form\RegistrationFormType();
    }
}
