<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityControllerregisterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.n_LpSm1.App\Infrastructure\Http\Security\Controller\SecurityController::register()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n_LpSm1.App\\Infrastructure\\Http\\Security\\Controller\\SecurityController::register()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userPasswordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'userPasswordHasher' => '?',
        ]))->withContext('App\\Infrastructure\\Http\\Security\\Controller\\SecurityController::register()', $container);
    }
}
