<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityControllerloginService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.xkWA7vv.App\Infrastructure\Http\Security\Controller\SecurityController::login()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xkWA7vv.App\\Infrastructure\\Http\\Security\\Controller\\SecurityController::login()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'authUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
        ], [
            'authUtils' => '?',
        ]))->withContext('App\\Infrastructure\\Http\\Security\\Controller\\SecurityController::login()', $container);
    }
}
