<?php

namespace ContainerAZwe317;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeacherControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Infrastructure\Http\Teacher\Controller\TeacherController' shared autowired service.
     *
     * @return \App\Infrastructure\Http\Teacher\Controller\TeacherController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Http/Teacher/Controller/TeacherController.php';
        include_once \dirname(__DIR__, 4).'/src/Application/Teacher/UseCase/GetTeacherHtmlData.php';

        $container->services['App\\Infrastructure\\Http\\Teacher\\Controller\\TeacherController'] = $instance = new \App\Infrastructure\Http\Teacher\Controller\TeacherController(($container->privates['App\\Application\\Teacher\\UseCase\\GetAllTeachers'] ?? $container->load('getGetAllTeachersService')), ($container->privates['App\\Application\\Teacher\\UseCase\\GetTeacher'] ?? $container->load('getGetTeacherService')), ($container->privates['App\\Application\\Teacher\\UseCase\\SelectTeachers'] ?? $container->load('getSelectTeachersService')), ($container->privates['App\\Application\\Teacher\\UseCase\\GetTeacherHtmlData'] ??= new \App\Application\Teacher\UseCase\GetTeacherHtmlData()));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Infrastructure\\Http\\Teacher\\Controller\\TeacherController', $container));

        return $instance;
    }
}
