<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAZwe317\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAZwe317/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerAZwe317.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerAZwe317\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerAZwe317\App_KernelTestDebugContainer([
    'container.build_hash' => 'AZwe317',
    'container.build_id' => '6415b822',
    'container.build_time' => 1753212362,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAZwe317');
