<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_logout_main' => [[], [], [], [['text', '/logout']], [], [], []],
    'homepage' => [[], ['_controller' => ['App\\Infrastructure\\Http\\HomePageController', 'index']], [], [['text', '/']], [], [], []],
    'health-check' => [[], ['_controller' => ['App\\Infrastructure\\Http\\HealthCheckAction', '__invoke']], [], [['text', '/health-check']], [], [], []],
    'app_login' => [[], ['_controller' => ['App\\Infrastructure\\Http\\Security\\Controller\\SecurityController', 'login']], [], [['text', '/login']], [], [], []],
    'app_profile' => [[], ['_controller' => ['App\\Infrastructure\\Http\\Security\\Controller\\SecurityController', 'profile']], [], [['text', '/profile']], [], [], []],
    'app_logout' => [[], ['_controller' => ['App\\Infrastructure\\Http\\Security\\Controller\\SecurityController', 'logout']], [], [['text', '/logout']], [], [], []],
    'app_register' => [[], ['_controller' => ['App\\Infrastructure\\Http\\Security\\Controller\\SecurityController', 'register']], [], [['text', '/register']], [], [], []],
    'select_teachers' => [[], ['_controller' => ['App\\Infrastructure\\Http\\Teacher\\Controller\\TeacherController', 'selectTeachers']], [], [['text', '/select_teachers']], [], [], []],
    'teachers_get_all' => [[], ['_controller' => ['App\\Infrastructure\\Http\\Teacher\\Controller\\TeacherController', 'getAll']], [], [['text', '/teachers']], [], [], []],
    'teacher_get_by_id' => [['id'], ['_controller' => ['App\\Infrastructure\\Http\\Teacher\\Controller\\TeacherController', 'getById']], ['id' => '[0-9]+'], [['variable', '/', '[0-9]+', 'id', true], ['text', '/teachers']], [], [], []],
];
