<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNKEgFe9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNKEgFe9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNKEgFe9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNKEgFe9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNKEgFe9\App_KernelDevDebugContainer([
    'container.build_hash' => 'NKEgFe9',
    'container.build_id' => '5933c414',
    'container.build_time' => 1761677713,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNKEgFe9');
